- name: Postgres service is enabled and started
  service:
    name: postgresql
    state: started
    enabled: true

- name: pg_hba.conf is configured
  lineinfile:
    dest: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    line: host    {{ item.database }}   {{ item.username }}   0.0.0.0/0 md5
  notify: Reload postgres
  with_items: "{{ postgres_databases }}"

- name: Postgres users are present
  postgresql_user:
    name: "{{ item.username }}"
    state: present
    password: "{{ item.password }}"
  become: True
  become_user: postgres
  with_items: "{{ postgres_databases }}"

- name: Postgres databases are present
  postgresql_db:
    name: "{{ item.database }}"
    encoding: 'UTF-8'
    template: 'template0'
    state: present
    owner: "{{ item.username }}"
  become: True
  become_user: postgres
  with_items: "{{ postgres_databases }}"

- name: Install backup script
  copy:
    content: "#!/bin/sh\npg_dump --blobs --clean | gzip > /var/local/backups/$1.$(date +%Y-%m-%d-%H:%M:%S).sql.gz\n"
    dest: /usr/local/sbin/awesto-pgbackup.sh
    owner: postgres
    group: postgres
    mode: 0700

- name: Install backup cronjob
  cron:
    name: "Postgres backup ({{ item.database }})"
    job: "/usr/local/sbin/pgbackup.sh {{ item.database }}"
    hour: 18
    minute: 0
    user: postgres

- name: Hourly backup cronjobs are present
  cron:
    user: "postgres"
    name: "Postgres backup for database {{ item.database }}"
    special_time: hourly
    job: "pg_dump -b -d {{ item.database }} | gzip > /var/local/backups/{{ item.database }}.`date +%Y-%m-%d-%H:%M:%S`.sql.gz"
  with_items: "{{ postgres_databases }}"
